version: '3.8'

services:
  reversedtetrisapi:
    image: reversed-tetris-api
    build:
      context: .
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
    ports:
      - "8080:8080"
    develop:
      watch:
        - action: rebuild
          path: ./
          target: /